- hosts: all

  vars:
    pip_install_packages:
      - name: docker-py

  tasks:
    - apt:
        name: "{{ item }}"
        update_cache: yes
        cache_valid_time: 300
      with_items:
        - dfc
        - htop
        - zile
  roles:
    - role: geerlingguy.pip
      pip_package: python3-pip
    - role: geerlingguy.docker
