- hosts: hass
  pre_tasks:
    - include_vars:
        file: "secret.yml"
  tasks:
    - community.docker.docker_container:
        name: cloudflare-ddns
        image: "oznu/cloudflare-ddns@sha256:19bd73d8aea9641dc329ec18ae693b2b9c33ff7cdc007f368266ce584446f995"
        env:
          API_KEY: "{{ cf_token }}"
          SUBDOMAIN: "{{ inventory_hostname }}"
          ZONE: djouce.eu
