- hosts: hass
  pre_tasks:
    - include_vars:
        file: "secret.yml"
  tasks:
    - apt:
        name:
          - snapd
          - usb-modeswitch # For the 4G Dongle
        update_cache: yes
        cache_valid_time: 300
    - community.general.snap:
        name:
          - home-assistant-snap
      register: hass
