- hosts: hass
  pre_tasks:
    - include_vars:
        file: "secret.yml"
  tasks:
    - apt:
        name:
          - snapd
          - usb-modeswitch # For the 4G Dongle
        update_cache: yes
        cache_valid_time: 300
    - community.general.snap:
        name:
          - home-assistant-snap
      register: hass
    # This is to allow access to /dev/... with CC25xx dongle (the error
    # looks like an AppArmor "DENIED" message)
    - ansible.builtin.command: snap connect home-assistant-snap:raw-usb
      when: hass.changed
    # TODO Could the namespace issue also be due to missing network
    # slot connection?
    - ansible.builtin.lineinfile:
        path: /var/snap/home-assistant-snap/current/configuration.yaml
        state: present
        insertafter: "default_config:"
        regexp: "^recorder"
        line: "recorder: { commit_interval: 60, purge_keep_days: 60 }"
      notify: Restart home-assistant
  handlers:
    - name: Restart home-assistant
      ansible.builtin.command: snap restart home-assistant-snap
