- hosts: hass
  tasks:
    - apt:
        name:
          - snapd
        update_cache: yes
        cache_valid_time: 300
    - community.general.snap:
        name:
          - home-assistant-snap
    - ansible.builtin.lineinfile:
        path: /var/snap/home-assistant-snap/current/configuration.yaml
        state: present
        insertafter: "default_config:"
        regexp: "^recorder"
        line: "recorder: { commit_interval: 60, purge_keep_days: 60 }"
      notify: Restart home-assistant
  handlers:
    - name: Restart home-assistant
      ansible.builtin.command: snap restart home-assistant-snap
