# All playbooks in the correct order

- import_playbook: ssh.yml
- import_playbook: basic.yml
- import_playbook: docker.yml
- import_playbook: ssl.yml
- import_playbook: opi.yml
- import_playbook: proxy.yml
- import_playbook: zabbix.yml
- import_playbook: zabbix-agent.yml
- import_playbook: syncthing.yml
- import_playbook: transmission.yml
