- hosts: orangepi
  tasks:
  - hostname:
      name: "{{ inventory_hostname }}"
  - copy:
      src: "files/test-if-wifi-died.sh"
      dest: /etc/test-if-wifi-died.sh
  - file:
      dest: /etc/test-if-wifi-died.sh
      mode: "u+x"
  # Workaround for watchdog-5.14
  # https://forum.armbian.com/topic/5526-orange-pi-pc-watchdog-service-bug/
  - lineinfile:
      path: /lib/systemd/system/watchdog.service
      insertafter: "[Install]"
      state: present
      line: "WantedBy=default.target"
  - systemd:
      daemon_reload: yes
      name: watchdog
      enabled: yes
      state: started
  - lineinfile:
      path: /boot/armbianEnv.txt
      regexp: '^overlays='
      state: present
      line: "overlays=analog-codec usbhost2 usbhost3"
    register: overlays
  - command: reboot
    when: overlays is changed
  - apt:
      name: "{{ item }}"
      state: present
    with_items:
      - vorbis-tools
      - sox
  roles:
    - role: whiskerlabs.watchdog
      watchdog_log_dir: /var/log/watchdog/
      watchdog_test_binary: /etc/test-if-wifi-died.sh
