- hosts: orangepi
  tasks:
  - hostname:
      name: "{{ inventory_hostname }}"
  - mount:
      src: "UUID={{ storage_uuid }}"
      path: /media
      fstype: ext4
      opts: errors=remount-ro,noexec,noatime,nodiratime
      state: mounted
      dump: 0
      passno: 2
  - cron:
      name: reboot
      month: "*"
      day: "*"
      dow: "*"
      hour: "0"
      minute: "*"
      job: reboot
  roles:
    - whiskerlabs.watchdog
