- hosts: orangepi
  tasks:
  - mount:
      src: "UUID={{ storage_uuid }}"
      path: /media
      fstype: ext4
      opts: errors=remount-ro,noexec,noatime,nodiratime
      state: mounted
      dump: 0
      passno: 2
  - cron:
      state: absent
      name: reboot-when-wifi-dies
      month: "*"
      day: "*"
      dow: "*"
      hour: "*"
      minute: "*"
      job: >-
        /bin/bash -c "dmesg | grep 'wsm_scan failed' && reboot"
  roles:
    - whiskerlabs.watchdog
