- hosts: orangepi
  tasks:
  - hostname:
      name: "{{ inventory_hostname }}"
  - mount:
      src: "UUID={{ storage_uuid }}"
      path: /media
      fstype: ext4
      opts: errors=remount-ro,noexec,noatime,nodiratime
      state: mounted
      dump: 0
      passno: 2
  - copy:
      src: "files/test-if-wifi-died.sh"
      dest: /etc/test-if-wifi-died.sh
  - file:
      dest: /etc/test-if-wifi-died.sh
      mode: "u+x"
  roles:
    - role: whiskerlabs.watchdog
      watchdog_log_dir: /var/log/watchdog/
      watchdog_test_binary: /etc/test-if-wifi-died.sh
