- hosts: proxy
  roles:
    - role: geerlingguy.pip
      pip_package: python3-pip
      pip_install_packages:
        - name: docker
          state: present
    - role: geerlingguy.docker
  tasks:
    - include_vars:
        file: 'secret.yml'
    - docker_container:
        name: mtproxy
        image: "dzhus/mtproxy:2018-08-02@sha256:cf7eb6602b9aa09eda5fd7171617050f9abfaea89481ac927ad38194af016aeb"
        published_ports:
          - "8443:443"
        volumes:
          - "{{ ansible_user_dir }}/mtproxy-config:/data"
        restart_policy: always
    - cron:
        name: "Restart MTProxy as recommended"
        hour: "3"
        minute: "0"
        job: "docker restart mtproxy"
    - docker_container:
        name: rss-to-telegram
        image: "dzhus/rss-to-telegram:2018-08-02-r1@sha256:95c17df814e2da4f71215dcb28d399f881c075a97935253de2e58eecdea6ce08"
        env:
          # Links obtained from https://instantview.telegram.org/my/
          R2T_MESSAGE_FORMAT: "[ ](https://t.me/iv?url={link}&rhash=56bc6e5c05a75e) {link}"
          R2T_URL: "https://dzhus.org/atom.xml"
          R2T_DESTINATION: "@dzhus"
          R2T_TOKEN: "{{ secret_rss_telegram_bot_token }}"
        restart_policy: always
