- oefenweb.fail2ban
- src: willshersystems.sshd
  version: v0.7.2
- jdauphant.ssl-certs
- geerlingguy.pip
- geerlingguy.docker
- oefenweb.swapfile
- dj-wasabi.telegraf
- whiskerlabs.watchdog
- manala.apt
- manala.influxdb # see dzhus/ansible-roles
- Stouts.grafana
