- hosts: all
  vars:
    my_user: dzhus
  pre_tasks:
    - user:
        name: "{{ my_user }}"
        # Local password = name
        password: $6$fvtSVxDeH2F9DsLB$gV4CCmzLGphGRFPTDg27MYbhyzH71FFjXCQXsLJ4fHCO0pqHxVAWyJaNUgOfk7RL7tCd217d1Wp4MczVbSsO8/
        groups:
          - adm
          - sudo
        append: yes
        shell: /bin/bash
    - authorized_key:
        user: "{{ my_user }}"
        key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCb33HWPPa0QuqKgpvMVJXeobh+WBt+wfvF7EGvhdJV65sLnoPq/U/MJ3KepYM3cNXdoXFjA6ClkxZ6llmBxwvoNShjwruUtRquG+wl0ahq7vq7INg5/ji9pUz4zOb69semFRSXPoX9OaNMR21YKf73/cNm05msJQ/9gQkciT4lC5d1FTB22LVxd7+9A5jjYPnblJSvhxL6jQ3cMgWJeAJIJLF3zg81eE1WS/fOFCCje6g0i00y3L/rnXGWV2x8Nh7BSnMr+X6aUw00eCP6FJhYvEGghMyQbvg+kmq/39RxGCgsiyyDX3uzr1yhotOF6Z3OzEcZM3nUJwbli6JC6vzR dzhus-yubikey-2017-08-09

  roles:
    - role: willshersystems.sshd
      sshd_UsePAM: no
      sshd_PasswordAuthentication: no
      sshd_PermitRootLogin: no

    - role: oefenweb.fail2ban
      fail2ban_bantime: 86400
