- hosts: tundra.dzhus.org
  pre_tasks:
    - include_vars:
        file: "secret.yml"
  vars:
    common_name: "{{ inventory_hostname }}"
    influx_dbname: telegraf
  roles:
    - role: manala.apt
      manala_apt_preferences:
        - "influxdb@influxdata"
        - "chronograf@influxdata"
    - role: jdauphant.ssl-certs
      ssl_certs_path_owner: "influxdb"
      ssl_certs_path_group: "influxdb"
      ssl_certs_common_name: "{{ common_name }}"
    - role: manala.influxdb
      manala_influxdb_config:
        - http:
          - auth-enabled: true
          - https-enabled: true
          - https-certificate:
              "/etc/ssl/{{ common_name }}/{{ common_name }}.pem"
          - https-private-key:
              "/etc/ssl/{{ common_name }}/{{ common_name }}.key"
      manala_influxdb_influx_bin: "/usr/bin/influx -ssl -unsafeSsl"
      manala_influxdb_admins:
        telegraf:
          name:     admin
          password: "{{ secret_influxdb_password_admin }}"
      manala_influxdb_databases:
        - "{{ influx_dbname }}"
      manala_influxdb_users:
        - database: "{{ influx_dbname }}"
          name:     chronograf
          password: "{{ secret_influxdb_password_chronograf }}"
        - database: "{{ influx_dbname }}"
          name:     telegraf
          password: "{{ secret_influxdb_password_telegraf }}"
      manala_influxdb_privileges:
        - database: "{{ influx_dbname }}"
          user:     chronograf
          grant:    ALL
        - database: "{{ influx_dbname }}"
          user:     telegraf
          grant:    WRITE
    - role: Stouts.grafana
      grafana_version: 5.2.2
      grafana_http_addr: 127.0.0.1
      grafana_provider: memory
      grafana_reporting_enabled: false
      grafana_check_for_updates: false
      grafana_allow_sign_up: false
      grafana_allow_org_create: false
  tasks:
    - apt:
        name: chronograf
        state: present
    - copy:
        dest: /etc/default/chronograf
        content: |
          HOST=127.0.0.1
          PORT=48080
          CANNED_PATH=/usr/share/chronograf/canned
          RESOURCES_PATH=/usr/share/chronograf/resources
      notify: Restart Chronograf
    - copy:
        dest: /usr/share/chronograf/resources/local.src
        content: |
          {
            "id": "31337",
            "name": "Local InfluxDB",
            "username": "chronograf",
            "password": "{{ secret_influxdb_password_chronograf }}",
            "url": "https://localhost:8086",
            "type": "influx",
            "insecureSkipVerify": true,
            "default": true,
            "telegraf": "{{ influx_dbname }}",
            "organization": "default"
          }
      notify: Restart Chronograf
    - grafana_datasource:
        name: "InfluxDB"
        access: proxy # server-to-server requests
        database: "{{ influx_dbname }}"
        ds_type: influxdb
        grafana_url: "http://localhost:3000"
        is_default: true
        user: "chronograf"
        password: "{{ secret_influxdb_password_chronograf }}"
        url: "https://localhost:8086"
        # + TODO Skip TLS Verification

    # DS_INFLUX_TELEGRAF variable has to be set from Grafana UI when
    # importing the dashboard, so we can't use this module here
    #
    # - get_url:
    #     url: https://grafana.com/api/dashboards/928/revisions/3/download
    #     dest: /var/tmp/telegraf-dashboard.json
    #     checksum: "sha256:da3b827eb57e3431bc37336ae2987d9e0ec9d5dc145aa65c6fae8a92d446cc14"
    # - grafana_dashboard:
    #     slug: "main"
    #     message: "Telegraf dashboard"
    #     path: /var/tmp/telegraf-dashboard.json
    #     grafana_url: "http://localhost:3000"
  handlers:
    - name: Restart Chronograf
      service:
        name: chronograf
        state: restarted
