- hosts: telegraf
  pre_tasks:
    - apt:
        package: lm-sensors
        state: present
  vars_prompt:
    - name: telegraf_influx_token
      prompt: Telegraf InfluxDB secret Token
  roles:
    - role: dj-wasabi.telegraf
      telegraf_agent_package_state: latest
      telegraf_agent_output:
        - type: influxdb_v2
          config:
            - urls = ["{{ telegraf_influx_url }}"]
            - token = "{{ telegraf_influx_token }}"
            - organization = "{{ telegraf_influx_org }}"
            - bucket = "{{ telegraf_influx_bucket }}"
      telegraf_plugins_default:
        - plugin: cpu
          config:
            - totalcpu = true
            - report_active = true
        - plugin: disk
          config:
            - mount_points = ["/"]
        - plugin: io
        - plugin: mem
        - plugin: kernel
        - plugin: system
        - plugin: temp
        - plugin: swap
        - plugin: net
        - plugin: processes
      notify: "Restart Telegraf"
