- hosts: tundra.dzhus.org
  vars:
    influx_cn: "{{ inventory_hostname }}"
  tasks:
    - name: "Download InfluxDB cert from {{ influx_cn }} central host"
      command: cat /etc/ssl/{{ influx_cn }}/{{ influx_cn }}.pem
      register: influx_cert
      changed_when: false
    - set_fact:
        influx_cert: "{{ influx_cert.stdout }}"

- hosts: telegraf
  pre_tasks:
    - include_vars:
        file: "secret.yml"
  roles:
    - role: dj-wasabi.telegraf
      telegraf_agent_output:
        - type: influxdb
          config:
            - urls = ["{{ telegraf_influx_url }}"]
            - database = "telegraf"
            - skip_database_creation = true
            - tls_ca = "/etc/telegraf/{{ telegraf_influx_cn }}.pem"
            - username = "telegraf"
            - password = "{{ secret_influxdb_password_telegraf }}"
      telegraf_plugins_default:
        - plugin: cpu
          config:
            - totalcpu = true
        - plugin: disk
          config:
            - mount_points = ["/", "/media"]
        - plugin: io
        - plugin: mem
        - plugin: kernel
        - plugin: system
        - plugin: swap
        - plugin: net
        - plugin: processes
  tasks:
    - name: Distribute the certificate on hosts with Telegraf
      copy:
        content: "{{ hostvars[telegraf_influx_cn]['influx_cert'] }}"
        dest: "/etc/telegraf/{{ telegraf_influx_cn }}.pem"
      notify: "Restart Telegraf"
