- hosts: tundra.dzhus.org
  pre_tasks:
    - include_vars:
        file: "secret.yml"
  vars:
    common_name: "{{ inventory_hostname }}"
  roles:
    - role: manala.apt
      manala_apt_preferences:
        - "influxdb@influxdata"
        - "chronograf@influxdata"
    - role: jdauphant.ssl-certs
      ssl_certs_path_owner: "influxdb"
      ssl_certs_path_group: "influxdb"
      ssl_certs_common_name: "{{ common_name }}"
    - role: manala.influxdb
      manala_influxdb_config:
        - http:
          - auth-enabled: true
          - https-enabled: true
          - https-certificate:
              "/etc/ssl/{{ common_name }}/{{ common_name }}.pem"
          - https-private-key:
              "/etc/ssl/{{ common_name }}/{{ common_name }}.key"
      manala_influxdb_influx_bin: "/usr/bin/influx -ssl -unsafeSsl"
      manala_influxdb_databases:
        - telegraf
      manala_influxdb_users:
        - database: telegraf
          name:     telegraf
          password: "{{ secret_influxdb_password }}"
      manala_influxdb_privileges:
        - database: telegraf
          user:     telegraf
          grant:    ALL
  tasks:
    - apt:
        name: chronograf
        state: present
    - copy:
        dest: /etc/default/chronograf
        content: |
          PORT=48080
          CANNED_PATH=/usr/share/chronograf/canned
          RESOURCES_PATH=/usr/share/chronograf/resources
      notify: Restart Chronograf
    - copy:
        dest: /usr/share/chronograf/resources/local.src
        content: |
          {
            "id": "31333",
            "name": "Local InfluxDB",
            "username": "telegraf",
            "password": "{{ secret_influxdb_password }}",
            "url": "https://localhost:8086",
            "type": "influx",
            "insecureSkipVerify": true,
            "default": true,
            "telegraf": "telegraf",
            "organization": "default"
          }
      notify: Restart Chronograf
  handlers:
    - name: Restart Chronograf
      service:
        name: chronograf
        state: restarted
