- hosts: telegraf
  pre_tasks:
    - include_vars:
        file: "secret.yml"
    - apt:
        package: lm-sensors
        state: present
  roles:
    - role: dj-wasabi.telegraf
      telegraf_agent_output:
        - type: influxdb_v2
          config:
            - urls = ["{{ telegraf_influx_url }}"]
            - token = "{{ telegraf_influx_token }}"
            - organization = "{{ telegraf_influx_org }}"
            - bucket = "{{ telegraf_influx_bucket }}"
      telegraf_plugins_default:
        - plugin: cpu
          config:
            - totalcpu = true
        - plugin: disk
          config:
            - mount_points = ["/", "/media"]
        - plugin: io
        - plugin: mem
        - plugin: kernel
        - plugin: system
        - plugin: sensors
        - plugin: swap
        - plugin: net
        - plugin: processes
      notify: "Restart Telegraf"
