- hosts: orangepi
  tasks:
    - name: Ensure NetworkManager retries infinitely
      notify: Reload NetworkManager
      ansible.builtin.lineinfile:
        path: /etc/NetworkManager/NetworkManager.conf
        # As per
        # http://manpages.ubuntu.com/manpages/focal/man5/NetworkManager.conf.5.html,
        # the defaults setting for autoconnect-retries-default is 4,
        # which means all connections will retry up to 4 times. This
        # can break connectivity if Wifi disappears for prolonged
        # periods of time, so we set it to 0 (infinite).
        state: absent
        insertafter: '\[main\]'
        line: autoconnect-retries-default=0
  handlers:
    - name: Reload NetworkManager
      ansible.builtin.service:
        name: network-manager
        state: reloaded
