- hosts: tundra.dzhus.org
  vars:
    # My GPG identity fingerprint
    encrypt_with_key: "0x81C38A63377EBC45"
    backup_filename: "zabbix-{{ ansible_fqdn }}-backup.sql.xz.gpg"
    backup_bucket: dzhus-backups
  pre_tasks:
    - docker_container:
        name: zabbix-postgres
        image: postgres:9.5
        env:
          POSTGRES_PASSWORD: zabbix
          POSTGRES_USER: zabbix
        restart_policy: always
      register: zabbix_db

    - docker_container:
        name: zabbix-server
        image: zabbix/zabbix-server-pgsql:alpine-latest
        links:
          - "zabbix-postgres:postgres-server"
        env:
          POSTGRES_PASSWORD: zabbix
          POSTGRES_USER: zabbix
        published_ports:
          - "10051:10051"
        restart_policy: always
        recreate: "{{ zabbix_db.changed }}"
      register: zabbix_server

    - docker_container:
        name: zabbix-web
        image: zabbix/zabbix-web-nginx-pgsql:alpine-latest
        links:
          - "zabbix-postgres:postgres-server"
          - "zabbix-server"
        env:
          TZ: Europe/Moscow
          ZBX_SERVER_NAME: "{{ ansible_fqdn }}"
          POSTGRES_PASSWORD: zabbix
          POSTGRES_USER: zabbix
        published_ports:
          - "34881:443"
        volumes:
          - "/etc/ssl/{{ ansible_fqdn }}:/etc/ssl/nginx:ro"
        restart_policy: always
        recreate: "{{ zabbix_server.changed }}"
    - terraform:
        project_path: "../terraform"
        state: present
      connection: local
      become: no
      # Don't really run `terraform apply`, just read outputs
      check_mode: yes
      register: terraform
    - fail:
        msg: "Could not see AWS key ID in terraform output (run terraform apply?)"
      when: terraform.outputs.backup_access_key_id is not defined
    - fail:
        msg: "Could not see AWS key secret in terraform output (run terraform apply?)"
      when: terraform.outputs.backup_secret_access_key is not defined
    - fail:
        msg: "Could not see bucket region in terraform output (run terraform apply?)"
      when: terraform.outputs.backup_bucket_region is not defined
    - apt:
        name: awscli
    - cron:
        name: "Backup Zabbix database to S3 every night"
        hour: "2"
        minute: "0"
        job: >
          gpg --fetch-keys 'http://pool.sks-keyservers.net/pks/lookup?op=get&search={{ encrypt_with_key }}' &&
          docker exec zabbix-postgres pg_dump -C zabbix -U postgres
          | xz
          | gpg --recipient {{ encrypt_with_key }} -e --trust-model=always
          > {{ backup_filename }} &&
          AWS_ACCESS_KEY_ID={{ terraform.outputs.backup_access_key_id.value }}
          AWS_SECRET_ACCESS_KEY={{ terraform.outputs.backup_secret_access_key.value }}
          AWS_DEFAULT_REGION={{ terraform.outputs.backup_bucket_region.value }}
          aws s3 mv {{ backup_filename }} s3://{{ backup_bucket }}
  roles:
    - role: dj-wasabi.zabbix-agent
      zabbix_agent_server: "{{ zabbix_server.ansible_facts.docker_container.NetworkSettings.IPAddress }}"
      zabbix_agent_serveractive: "{{ zabbix_server.ansible_facts.docker_container.NetworkSettings.IPAddress }}"
      zabbix_agent_hostname: "{{ ansible_fqdn }}"
