- hosts: zabbix-agent
  pre_tasks:
    - include_vars:
        file: 'secret.yml'

    # On OrangePi's, install custom packages, see
    # https://github.com/imkebe/zabbix3-rpi/issues/1#issuecomment-336121438
    - apt_key:
        keyserver: keyserver.ubuntu.com
        id: 1DFF230644068194
      when: ansible_architecture == "armv7l"
    - apt_repository:
        repo: deb https://repo.fredprod.com/ jessie main
      when: ansible_architecture == "armv7l"
  roles:
    # For boxes with no external IP, use templates with active checks
    # with https://github.com/mingfang/zabbix-templates
    #
    # Hosts with matching hostnames need to be created on Zabbix
    # server too. There's no built-in way to auto-register agents
    # using TLS/PSK, see
    # https://support.zabbix.com/browse/ZBXNEXT-3497
    #
    # See also
    # https://www.fontenay-ronan.fr/zabbix-monitor-a-device-behind-a-nat-firewall/
    - role: dj-wasabi.zabbix-agent
      zabbix_agent_serveractive: "tundra.dzhus.org"
      zabbix_agent_hostname: "{{ inventory_hostname }}"
      zabbix_agent_tlsconnect: "psk"
      zabbix_agent_tlsaccept: "psk"
      zabbix_agent_tlspskidentity: "{{ secret_zabbix_psk_identity }}"
      zabbix_agent_tlspskfile: "/etc/zabbix/psk.key"
      zabbix_agent_tlspsk_secret: "{{ secret_zabbix_psk }}"
  tasks:
    # Missing on Armbian 5.38
    - file:
        path: /var/log/zabbix
        state: directory
        owner: zabbix
        group: zabbix
